# -----------------------------------------------
# !!! THIS FILE WAS GENERATED BY TYPE-GRAPHQL !!!
# !!!   DO NOT MODIFY THIS FILE BY YOURSELF   !!!
# -----------------------------------------------

type Mutation {
  sendMessage(author: String!, text: String!): TestMessage!
}

type Query {
  testMessages: [TestMessage!]!
}

type Subscription {
  testMessageSent: TestMessage
}

type TestMessage {
  id: String!
  text: String!
  author: String!
}
